### ISSUE TITLE
MongoDB ssb2 bug  PlayerLoginEvent

### ISSUE THREAD

**Issue by heeaart** [BG-Software-LLC/SuperiorSkyblock-MongoDB#1]
### Minecraft's Version

1.19.1

### Plugin's Version

SSB-MongoDB-b9.jar

### Describe the bug

[22:57:16 INFO]: UUID of player heeaart is f2120c86-3ce8-4eb1-a8e7-2abfe4063582
[22:57:16 ERROR]: Could not pass event PlayerLoginEvent to SuperiorSkyblock2 v2022.8.1-b858
java.lang.AbstractMethodError: Receiver class com.bgsoftware.superiorskyblock.module.mongodb.bridge.MongoDatabaseBridge does not define or inherit an implementation of the resolved method 'abstract com.bgsoftware.superiorskyblock.api.data.DatabaseBridgeMode getDatabaseBridgeMode()' of interface com.bgsoftware.superiorskyblock.api.data.DatabaseBridge.
        at com.bgsoftware.superiorskyblock.core.database.bridge.PlayersDatabaseBridge.runOperationIfRunning(PlayersDatabaseBridge.java:248) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.core.database.bridge.PlayersDatabaseBridge.insertPlayer(PlayersDatabaseBridge.java:121) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.player.PlayersManagerImpl.getSuperiorPlayer(PlayersManagerImpl.java:58) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.player.PlayersManagerImpl.getSuperiorPlayer(PlayersManagerImpl.java:47) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.listener.PlayersListener.onPlayerLogin(PlayersListener.java:82) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:git-Purpur-1738]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:785) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:194) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:95) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:577) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1610) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
2022-10-10 22:57:16,730 Netty Epoll Server IO #1 ERROR Recursive call to appender Async
[22:57:16 ERROR]: [SuperiorSkyblock2] Unhandled exception occurred in onPacketReceiving(PacketEvent) for SuperiorSkyblock2
java.lang.AbstractMethodError: Receiver class com.bgsoftware.superiorskyblock.module.mongodb.bridge.MongoDatabaseBridge does not define or inherit an implementation of the resolved method 'abstract com.bgsoftware.superiorskyblock.api.data.DatabaseBridgeMode getDatabaseBridgeMode()' of interface com.bgsoftware.superiorskyblock.api.data.DatabaseBridge.
        at com.bgsoftware.superiorskyblock.core.database.bridge.PlayersDatabaseBridge.runOperationIfRunning(PlayersDatabaseBridge.java:248) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.core.database.bridge.PlayersDatabaseBridge.saveUserLocale(PlayersDatabaseBridge.java:46) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.setUserLocale(SSuperiorPlayer.java:488) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.external.ProtocolLibHook$ChangePlayerLanguageListener.onPacketReceiving(ProtocolLibHook.java:50) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:549) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:514) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:117) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:506) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33) ~[ProtocolLib.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:57:16 ERROR]: Could not pass event PlayerJoinEvent to SuperiorSkyblock2 v2022.8.1-b858
java.lang.AbstractMethodError: Receiver class com.bgsoftware.superiorskyblock.module.mongodb.bridge.MongoDatabaseBridge does not define or inherit an implementation of the resolved method 'abstract com.bgsoftware.superiorskyblock.api.data.DatabaseBridgeMode getDatabaseBridgeMode()' of interface com.bgsoftware.superiorskyblock.api.data.DatabaseBridge.
        at com.bgsoftware.superiorskyblock.core.database.bridge.PlayersDatabaseBridge.runOperationIfRunning(PlayersDatabaseBridge.java:248) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.core.database.bridge.PlayersDatabaseBridge.saveLastTimeStatus(PlayersDatabaseBridge.java:88) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.setLastTimeStatus(SSuperiorPlayer.java:179) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.player.SSuperiorPlayer.updateLastTimeStatus(SSuperiorPlayer.java:170) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.bgsoftware.superiorskyblock.listener.PlayersListener.onPlayerJoin(PlayersListener.java:106) ~[SuperiorSkyblock2-2022.8.1-b858.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:git-Purpur-1738]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:366) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:308) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:369) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:588) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1610) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1738]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:57:16 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayInSettings@3bdd233f[
    b=pl_PL
    c=15
    d=FULL
    e=true
    f=127
    g=RIGHT
    h=true
    i=true
  ]

### To Reproduce

plugins version:

SSB-MongoDB-b9.jar
SuperiorSkyblock2-2022.8.1-b858.jar

### Additional Information

Could not pass event PlayerLoginEvent to SuperiorSkyblock2 v2022.8.1-b858

**Comment by OmerBenGera** [comment]
Check out latest dev build of the module, let me know if it works.

**Comment by OmerBenGera** [comment]
I am closing this as it should be fixed.
If the issue still occurs let me know
