### ISSUE TITLE
MongoDB ssb2 bug [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin

### ISSUE THREAD

**Issue by heeaart** [BG-Software-LLC/SuperiorSkyblock-MongoDB#2]
### Minecraft's Version

1.19.1

### Plugin's Version

plugins version:

SSB-MongoDB-b11.jar
SuperiorSkyblock2-2022.8.1-b858.jar

### Describe the bug

[23:27:06 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
[23:27:06 WARN]: java.lang.NoSuchMethodError: 'com.mongodb.client.result.InsertOneResult com.mongodb.client.MongoCollection.insertOne(java.lang.Object)'
[23:27:06 WARN]:        at com.bgsoftware.superiorskyblock.module.mongodb.MongoDBInitializer.initDatabase(MongoDBInitializer.java:13)
[23:27:06 WARN]:        at com.bgsoftware.superiorskyblock.module.mongodb.MongoDBModule.onEnable(MongoDBModule.java:43)
[23:27:06 WARN]:        at SuperiorSkyblock2-2022.8.1-b858.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:120)
[23:27:06 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[23:27:06 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[23:27:06 WARN]:        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[23:27:06 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[23:27:06 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[23:27:06 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[23:27:06 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[23:27:06 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[23:27:06 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[23:27:06 WARN]:        at SuperiorSkyblock2-2022.8.1-b858.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:160)
[23:27:06 WARN]:        at SuperiorSkyblock2-2022.8.1-b858.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:513)
[23:27:06 WARN]:        at SuperiorSkyblock2-2022.8.1-b858.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:253)
[23:27:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[23:27:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[23:27:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548)
[23:27:06 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:594)
[23:27:06 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:508)
[23:27:06 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[23:27:06 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427)
[23:27:06 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:342)
[23:27:06 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1140)
[23:27:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[23:27:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

try create db 

### Additional Information

[SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:

**Comment by OmerBenGera** [comment]
Try it on a server with only SSB and the module installed, let me know if it still occurs.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by heeaart** [comment]
same problem

**Comment by OmerBenGera** [comment]
> same problem

What version of Spigot do you use?

**Comment by heeaart** [comment]
1.19.1

**Comment by OmerBenGera** [comment]
> 1.19.1

/version output please, this is not enough information about your version.

**Comment by heeaart** [comment]
Current: git-Purpur-1738 (MC: 1.19.1)*
Previous: git-Purpur-1777 (MC: 1.19.2)
* You are 13 version(s) behind
Download the new version at: https://purpurmc.org/downloads

**Comment by heeaart** [comment]
![image](https://user-images.githubusercontent.com/68756645/199270555-6a3716ed-cf4b-40f5-a079-64d4232352c6.png)

**Comment by OmerBenGera** [comment]
Sorry for the long waiting time
I can't seem to replicate the issue using your purpur version (and latest SSB)

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by heeaart** [comment]
Maybe my mongo connection worst?
'mongodb+srv://name:password@mongo1.example.pl/'

**Comment by OmerBenGera** [comment]
> Maybe my mongo connection worst? 'mongodb+srv://name:[password@mongo1.example.pl](mailto:password@mongo1.example.pl)/'

Shouldn't matter
The method that is used to insert data is not used
I'd guess just don't use MongoDB

**Comment by OmerBenGera** [comment]
Is this still relevant?
